'use client'
import { useState } from 'react'
export default function RelationshipPage(){
  const [a, setA] = useState({ name:'', dob:'', tob:'', place:'' })
  const [b, setB] = useState({ name:'', dob:'', tob:'', place:'' })
  const [goal, setGoal] = useState('heal')
  const [json, setJson] = useState('')
  async function analyze(){ const r = await fetch('/api/relationship/compatibility', { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ a, b, goal }) }); const j = await r.json(); setJson(j.analysis) }
  return (<main className="min-h-screen pt-28 pb-16 px-6 max-w-5xl mx-auto"><h1 className="text-4xl font-semibold">Relationship</h1><p className="text-slate-300 mt-2">Compatibility analyzer — free JSON preview.</p><div className="mt-6 grid md:grid-cols-2 gap-6"><div className="rounded-2xl border border-white/10 bg-white/5 p-4"><h3 className="font-semibold mb-2">Profile A</h3><input placeholder="Full name" className="w-full px-3 py-2 rounded-xl bg-white/5 border border-white/10" onChange={e=>setA({...a,name:e.target.value})}/><input placeholder="DOB (YYYY-MM-DD)" className="w-full mt-2 px-3 py-2 rounded-xl bg-white/5 border border-white/10" onChange={e=>setA({...a,dob:e.target.value})}/><input placeholder="TOB (hh:mm)" className="w-full mt-2 px-3 py-2 rounded-xl bg-white/5 border border-white/10" onChange={e=>setA({...a,tob:e.target.value})}/><input placeholder="Place of birth" className="w-full mt-2 px-3 py-2 rounded-xl bg-white/5 border border-white/10" onChange={e=>setA({...a,place:e.target.value})}/></div><div className="rounded-2xl border border-white/10 bg-white/5 p-4"><h3 className="font-semibold mb-2">Profile B</h3><input placeholder="Full name" className="w-full px-3 py-2 rounded-xl bg-white/5 border border-white/10" onChange={e=>setB({...b,name:e.target.value})}/><input placeholder="DOB (YYYY-MM-DD)" className="w-full mt-2 px-3 py-2 rounded-xl bg-white/5 border border-white/10" onChange={e=>setB({...b,dob:e.target.value})}/><input placeholder="TOB (hh:mm)" className="w-full mt-2 px-3 py-2 rounded-xl bg-white/5 border border-white/10" onChange={e=>setB({...b,tob:e.target.value})}/><input placeholder="Place of birth" className="w-full mt-2 px-3 py-2 rounded-xl bg-white/5 border border-white/10" onChange={e=>setB({...b,place:e.target.value})}/></div></div><div className="mt-4"><select className="px-3 py-2 rounded-xl bg-white/5 border border-white/10" onChange={e=>setGoal(e.target.value)}><option value="heal">Heal</option><option value="trust">Trust</option><option value="intimacy">Intimacy</option><option value="boundaries">Boundaries</option><option value="growth">Growth</option></select></div><button onClick={analyze} className="mt-4 px-5 py-3 rounded-xl bg-teal-300 text-black font-semibold">Analyze</button>{json && (<pre className="mt-4 rounded-2xl border border-white/10 bg-white/5 p-4 text-xs text-slate-200 overflow-auto">{json}</pre>)}<p className="mt-6 text-slate-300">Want a polished PDF + 7‑day repair plan? <a className="underline" href="/services#lead">Book now</a>.</p></main>)
}
